openapi: 3.0.2
info:
  title: Co-WIN Public APIs
  description: "Co-WIN Public APIs to find appointment availabilty and to download\
    \ vaccination certificates. These APIs are available for use by all third party\
    \ applications. <i>[Updated on 30 Apr 2021]</i>"
  termsOfService: https://www.cowin.gov.in/terms-condition
  contact:
    name: Ministry of Health and Family Welfare
    url: https://www.cowin.gov.in
  version: 1.1.0
servers:
- url: https://cdn-api.co-vin.in/api
  description: Production Server
paths:
  /v2/auth/public/generateOTP:
    post:
      tags:
      - User Authentication APIs
      summary: Authenticate a beneficiary by Mobile/OTP
      description: Initiate beneficiary authentication using mobile and OTP
      operationId: generateOTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated access!
        "500":
          description: Internal Server Error
  /v2/auth/public/confirmOTP:
    post:
      tags:
      - User Authentication APIs
      summary: Confirm mobile OTP for authentication
      description: API to confirm the OTP for authentication.
      operationId: confirmOTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
  /v2/admin/location/states:
    get:
      tags:
      - Metadata APIs
      summary: Get states
      description: API to get all the states in India.
      operationId: states
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
            examples: {}
        "401":
          description: Unauthenticated access!
        "500":
          description: Internal Server Error
  /v2/admin/location/districts/{state_id}:
    get:
      tags:
      - Metadata APIs
      summary: Get list of districts
      description: API to get all the districts.
      operationId: districts
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      - name: state_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: "16"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
            examples: {}
        "401":
          description: Unauthenticated access!
        "500":
          description: Internal Server Error
  /v2/appointment/sessions/public/findByPin:
    get:
      tags:
      - Appointment Availability APIs
      summary: Get vaccination sessions by PIN
      description: API to get planned vaccination sessions on a specific date in a
        given pin.
      operationId: findByPin
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      - name: pincode
        in: query
        required: true
        style: form
        explode: true
        schema:
          minLength: 3
          type: string
          example: "110001"
      - name: date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 31-03-2021
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
  /v2/appointment/sessions/public/findByDistrict:
    get:
      tags:
      - Appointment Availability APIs
      summary: Get vaccination sessions by district
      description: API to get planned vaccination sessions on a specific date in a
        given district.
      operationId: findByDistrict
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      - name: district_id
        in: query
        required: true
        style: form
        explode: true
        schema:
          minLength: 3
          type: string
          example: "512"
      - name: date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 31-03-2021
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
  /v2/appointment/sessions/public/calendarByPin:
    get:
      tags:
      - Appointment Availability APIs
      summary: Get vaccination sessions by PIN for 7 days
      description: API to get planned vaccination sessions for 7 days from a specific
        date in a given pin.
      operationId: calendarByPin
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      - name: pincode
        in: query
        required: true
        style: form
        explode: true
        schema:
          minLength: 3
          type: string
          example: "110001"
      - name: date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 31-03-2021
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
  /v2/appointment/sessions/public/calendarByDistrict:
    get:
      tags:
      - Appointment Availability APIs
      summary: Get vaccination sessions by district for 7 days
      description: API to get planned vaccination sessions for 7 days from a specific
        date in a given district.
      operationId: calendarByDistrict
      parameters:
      - name: Accept-Language
        in: header
        description: The locate code of the preferred language such as en_US. The
          text data will be returned in the preferred language along with default
          English text.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: hi_IN
      - name: district_id
        in: query
        required: true
        style: form
        explode: true
        schema:
          minLength: 3
          type: string
          example: "512"
      - name: date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 31-03-2021
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
  /v2/registration/certificate/public/download:
    get:
      tags:
      - Certificate APIs
      summary: Download vaccination certificate in PDF format by beneficiary reference
        id
      description: API to download vaccination certificate in PDF format by beneficiary
        reference id. This API requires a <i>Bearer</i> token acquired with user mobile
        OTP validation as defined in User Authentication APIs.
      operationId: download
      parameters:
      - name: beneficiary_reference_id
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: "1234567890123"
      responses:
        "200":
          description: Successful Operation
          content:
            application/pdf:
              schema:
                type: string
                format: binary
                x-content-type: application/pdf
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthenticated Access
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
components:
  schemas:
    CenterResponseSchema:
      required:
      - block_name
      - center_id
      - district_name
      - fee_type
      - from
      - name
      - pincode
      - state_name
      - to
      type: object
      properties:
        center_id:
          minLength: 1
          type: number
          example: 1234
        name:
          minLength: 1
          type: string
          example: District General Hostpital
        name_l:
          minLength: 1
          type: string
          description: Name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        state_name:
          type: string
          example: Maharashtra
        state_name_l:
          minLength: 1
          type: string
          description: State name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        district_name:
          type: string
          example: Satara
        district_name_l:
          minLength: 1
          type: string
          description: District name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        block_name:
          type: string
          example: Jaoli
        block_name_l:
          minLength: 1
          type: string
          description: Block name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        pincode:
          type: string
          example: "413608"
        lat:
          maximum: 37.1
          minimum: 8.06
          type: number
          format: float
          example: 28.7
        long:
          maximum: 97.41
          minimum: 68.11
          type: number
          format: float
          example: 77.1
        from:
          type: string
          format: partial-time
          example: 09:00:00
        to:
          type: string
          format: partial-time
          example: 18:00:00
        fee_type:
          type: string
          description: Fee charged for vaccination
          example: Paid
          enum:
          - Free
          - Paid
    SessionsSchema:
      uniqueItems: true
      type: array
      items:
        $ref: '#/components/schemas/SessionResponseSchema'
      x-schema-name: SessionsSchema
    SessionResponseSchema:
      allOf:
      - $ref: '#/components/schemas/CenterResponseSchema'
      - required:
        - available_capacity
        - block_name
        - center_id
        - date
        - district_name
        - fee
        - fee_type
        - from
        - min_age_limit
        - name
        - pincode
        - session_id
        - slots
        - state_name
        - to
        - vaccine
        type: object
        properties:
          fee:
            type: string
            example: "250"
          session_id:
            minLength: 1
            type: string
            format: uuid
          date:
            minLength: 1
            type: string
            example: 31-05-2021
          available_capacity:
            type: number
            example: 50
          min_age_limit:
            type: number
            example: 18
          vaccine:
            type: string
            example: COVISHIELD
          slots:
            minItems: 1
            uniqueItems: true
            type: array
            description: Array of slot names
            example:
            - FORENOON
            - AFTERNOON
            items:
              type: string
    SessionCalendarEntriesSchema:
      uniqueItems: true
      type: array
      items:
        $ref: '#/components/schemas/SessionCalendarEntrySchema'
      x-schema-name: SessionCalendarEntriesSchema
    SessionCalendarEntrySchema:
      required:
      - block_name
      - center_id
      - district_name
      - fee_type
      - from
      - name
      - pincode
      - sessions
      - state_name
      - to
      type: object
      properties:
        center_id:
          minLength: 1
          type: number
          example: 1234
        name:
          minLength: 1
          type: string
          example: District General Hostpital
        name_l:
          minLength: 1
          type: string
          description: Name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        state_name:
          type: string
          example: Maharashtra
        state_name_l:
          minLength: 1
          type: string
          description: State name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        district_name:
          type: string
          example: Satara
        district_name_l:
          minLength: 1
          type: string
          description: District name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        block_name:
          type: string
          example: Jaoli
        block_name_l:
          minLength: 1
          type: string
          description: Block name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
        pincode:
          type: string
          example: "413608"
        lat:
          maximum: 37.1
          minimum: 8.06
          type: number
          format: float
          example: 28.7
        long:
          maximum: 97.41
          minimum: 68.11
          type: number
          format: float
          example: 77.1
        from:
          type: string
          format: partial-time
          example: 09:00:00
        to:
          type: string
          format: partial-time
          example: 18:00:00
        fee_type:
          type: string
          description: Fee charged for vaccination
          example: Free
          enum:
          - Free
          - Paid
        vaccine_fees:
          $ref: '#/components/schemas/VaccineFeeListSchema'
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionCalendarEntrySchema_sessions'
      example:
        pincode: "413608"
        sessions:
        - date: 31-05-2021
          vaccine: COVISHIELD
          slots:
          - FORENOON
          - AFTERNOON
          min_age_limit: 18
          session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          available_capacity: 50
        - date: 31-05-2021
          vaccine: COVISHIELD
          slots:
          - FORENOON
          - AFTERNOON
          min_age_limit: 18
          session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          available_capacity: 50
        vaccine_fees:
        - vaccine: COVISHIELD
          fee: "250"
        - vaccine: COVISHIELD
          fee: "250"
        district_name_l: ""
        name_l: ""
        fee_type: Free
        state_name_l: ""
        long: 77.1
        district_name: Satara
        block_name: Jaoli
        block_name_l: ""
        center_id: 1234
        state_name: Maharashtra
        name: District General Hostpital
        from: 09:00:00
        to: 18:00:00
        lat: 28.7
    VaccineFeeListSchema:
      uniqueItems: true
      type: array
      items:
        $ref: '#/components/schemas/VaccineFeeSchema'
      x-schema-name: VaccineFeeListSchema
    VaccineFeeSchema:
      required:
      - fee
      - vaccine
      type: object
      properties:
        vaccine:
          type: string
          example: COVISHIELD
        fee:
          type: string
          example: "250"
      example:
        vaccine: COVISHIELD
        fee: "250"
    body:
      type: object
      properties:
        mobile:
          minItems: 1
          type: string
          example: "9876543210"
    inline_response_200:
      type: object
      properties:
        txnId:
          minItems: 1
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      example:
        txnId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    inline_response_400:
      type: object
      properties:
        errorCode:
          type: string
          example: USRRES0001
        error:
          type: string
          example: Input parameter missing
    body_1:
      type: object
      properties:
        otp:
          minLength: 64
          type: string
          description: SHA256 of the OTP
          example: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
        txnId:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    inline_response_200_1:
      type: object
      properties:
        token:
          type: string
      example:
        token: token
    inline_response_200_2:
      type: object
      properties:
        states:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_2_states'
        ttl:
          type: number
          description: Time in hours to cache the data. Client applications can use
            this data for this many number of hours before calling this API again.
      example:
        ttl: 0.8008281904610115
        states:
        - state_name: Andaman and Nicobar Islands
          state_id: 58
          state_name_l: ""
        - state_name: Andaman and Nicobar Islands
          state_id: 58
          state_name_l: ""
    inline_response_200_3:
      type: object
      properties:
        districts:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_3_districts'
        ttl:
          type: number
          description: Time in hours to cache the data. Client applications can use
            this data for this many number of hours before calling this API again.
      example:
        districts:
        - district_name: Ahmednagar
          district_name_l: ""
          state_id: 16
          district_id: 391
        - district_name: Ahmednagar
          district_name_l: ""
          state_id: 16
          district_id: 391
        ttl: 0.8008281904610115
    inline_response_200_4:
      properties:
        sessions:
          $ref: '#/components/schemas/SessionsSchema'
      example:
        sessions:
        - ""
        - ""
    inline_response_200_5:
      properties:
        centers:
          $ref: '#/components/schemas/SessionCalendarEntriesSchema'
      example:
        centers:
        - pincode: "413608"
          sessions:
          - date: 31-05-2021
            vaccine: COVISHIELD
            slots:
            - FORENOON
            - AFTERNOON
            min_age_limit: 18
            session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            available_capacity: 50
          - date: 31-05-2021
            vaccine: COVISHIELD
            slots:
            - FORENOON
            - AFTERNOON
            min_age_limit: 18
            session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            available_capacity: 50
          vaccine_fees:
          - vaccine: COVISHIELD
            fee: "250"
          - vaccine: COVISHIELD
            fee: "250"
          district_name_l: ""
          name_l: ""
          fee_type: Free
          state_name_l: ""
          long: 77.1
          district_name: Satara
          block_name: Jaoli
          block_name_l: ""
          center_id: 1234
          state_name: Maharashtra
          name: District General Hostpital
          from: 09:00:00
          to: 18:00:00
          lat: 28.7
        - pincode: "413608"
          sessions:
          - date: 31-05-2021
            vaccine: COVISHIELD
            slots:
            - FORENOON
            - AFTERNOON
            min_age_limit: 18
            session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            available_capacity: 50
          - date: 31-05-2021
            vaccine: COVISHIELD
            slots:
            - FORENOON
            - AFTERNOON
            min_age_limit: 18
            session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            available_capacity: 50
          vaccine_fees:
          - vaccine: COVISHIELD
            fee: "250"
          - vaccine: COVISHIELD
            fee: "250"
          district_name_l: ""
          name_l: ""
          fee_type: Free
          state_name_l: ""
          long: 77.1
          district_name: Satara
          block_name: Jaoli
          block_name_l: ""
          center_id: 1234
          state_name: Maharashtra
          name: District General Hostpital
          from: 09:00:00
          to: 18:00:00
          lat: 28.7
    SessionCalendarEntrySchema_sessions:
      required:
      - available_capacity
      - date
      - fee
      - fee_type
      - from
      - min_age_limit
      - session_id
      - slots
      - to
      - vaccine
      type: object
      properties:
        session_id:
          minLength: 1
          type: string
          format: uuid
        date:
          minLength: 1
          type: string
          example: 31-05-2021
        available_capacity:
          type: number
          example: 50
        min_age_limit:
          type: number
          example: 18
        vaccine:
          type: string
          example: COVISHIELD
        slots:
          minItems: 1
          uniqueItems: true
          type: array
          description: Array of slot names
          example:
          - FORENOON
          - AFTERNOON
          items:
            type: string
      example:
        date: 31-05-2021
        vaccine: COVISHIELD
        slots:
        - FORENOON
        - AFTERNOON
        min_age_limit: 18
        session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        available_capacity: 50
    inline_response_200_2_states:
      required:
      - state_id
      - state_name
      type: object
      properties:
        state_id:
          type: number
          example: 58
        state_name:
          minLength: 1
          type: string
          example: Andaman and Nicobar Islands
        state_name_l:
          minLength: 1
          type: string
          description: State name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
      example:
        state_name: Andaman and Nicobar Islands
        state_id: 58
        state_name_l: ""
    inline_response_200_3_districts:
      required:
      - district_id
      - district_name
      type: object
      properties:
        state_id:
          type: number
          example: 16
        district_id:
          type: number
          example: 391
        district_name:
          minLength: 1
          type: string
          example: Ahmednagar
        district_name_l:
          minLength: 1
          type: string
          description: District name in preferred language as specified in Accept-Language
            header parameter.
          example: ""
      example:
        district_name: Ahmednagar
        district_name_l: ""
        state_id: 16
        district_id: 391
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
